### ISSUE TITLE
Remove x86 version of libsteam_api

### ISSUE THREAD

**Issue by skibitsky** [xsolla/store-unity-sdk#58]
Hello,

I get the following error when building for macOS:
```
Plugin 'libsteam_api.so' is used from several locations:
 Assets/Xsolla/ThirdParty/Steamworks.NET-master/Plugins/x86/libsteam_api.so would be copied to <PluginPath>/libsteam_api.so
 Assets/Xsolla/ThirdParty/Steamworks.NET-master/Plugins/x86_64/libsteam_api.so would be copied to <PluginPath>/libsteam_api.so
Please fix plugin settings and try again.

UnityEditor.Modules.DefaultPluginImporterExtension:CheckFileCollisions(String)
UnityEditorInternal.PluginsHelper:CheckFileCollisions(BuildTarget) (at /Users/bokken/buildslave/unity/build/Editor/Mono/Plugins/PluginsHelper.cs:25)
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr) (at /Users/bokken/buildslave/unity/build/Modules/IMGUI/GUIUtility.cs:197)
```

The 32bit Windows [was removed](https://github.com/xsolla/store-unity-sdk/commit/c2a1bbed4893d524829e566afebc9ed3263e2852#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5L47) from the list of supported targets in the last commit .

I propose to remove `Assets/Xsolla/ThirdParty/Steamworks.NET-master/Plugins/x86` because it's no longer needed.

Unity  2019.4.14f1 LTS
macOS Big Sur 11.0.1

**Comment by LeonidRatanov** [comment]
Hi @skibitsky !
Fixed in version 0.6.4.0
Thanks!
