### ISSUE TITLE
Error in XsollaAuth.DeviceID.cs

### ISSUE THREAD

**Issue by dmbond** [xsolla/store-unity-sdk#60]
https://github.com/xsolla/store-unity-sdk/blob/master/Assets/Xsolla/Auth/Api/XsollaAuth.DeviceID.cs#L26
but not using in
https://github.com/xsolla/store-unity-sdk/blob/master/Assets/Xsolla/Auth/Api/XsollaAuth.DeviceID.cs#L32
and
URL: https://login.xsolla.com/api/oauth2/login/device/Android?...
RESPONSE: {"error":{"code":0,"description":"device_type in path should be one of [android ios]"}}

**Comment by AlexeiDemonov** [comment]
Thank you, we'll check and hotfix if needed.

**Comment by AlexeiDemonov** [comment]
Thank you again, the problem has been solved in 1.2.1 release
