### ISSUE TITLE
Project ID not consistent

### ISSUE THREAD

**Issue by dmbond** [xsolla/store-unity-sdk#61]
Я не менял другие значения, возможно с ними тоже такая магия творится. Наверное из-за того что они хранятся и в PlayerPrefs и в XsollaSettings.asset или может в логике ошибка, происходит рассинхронизация того что показывает Unity Inspector для XsollaSettings и того что хранится в файле. У меня нет четкого описания как воспроизвести, просто изменяя значения в инспекторе (и сохраняя проект на всякий случай) наблюдайте за содержимым XsollaSettings.asset. У меня там оказывался 0 или значение Project ID для демки.

**Comment by AlexeiDemonov** [comment]
Спасибо. Проверим и исправим.
