### ISSUE TITLE
Remove the Always embed swift libraries flag

### ISSUE THREAD

**Issue by dmbond** [xsolla/store-unity-sdk#64]
У вас в
https://github.com/xsolla/store-unity-sdk/blob/1c55f381f59d55f85f9997d93ce309acac7cc494/Assets/Xsolla/Core/Editor/iOSBuildPostProcess.cs#L45
но это в некоторых случаях приводит к невозможности залить билд в стор.
В EDM начиная с 1.2.172 отказались от его установки 
https://github.com/googlesamples/unity-jar-resolver/pull/526

**Comment by DenisRakhimovXsolla** [comment]
Спасибо за замечание. 
Уже исправлено, войдет в ближайший релиз, который будет буквально на этой неделе
