### ISSUE TITLE
Bug: WebRequestHelper instance gets destroyed when scene unloads

### ISSUE THREAD

**Issue by AntonPetrov83** [xsolla/store-unity-sdk#65]
Hi!

`WebRequestHelper` instance gets destroyed when scene unloads. Adding `DontDestroyOnLoad` fixes the issue.

And you follow similar pattern in other classes too: `XsollaWebCallbacks`, `AndroidHelper` etc.

**Comment by DenisRakhimovXsolla** [comment]
Hey, @AntonPetrov83 !
Thank you for you issue
Will be fixed in next release

**Comment by DenisRakhimovXsolla** [comment]
Fixed in version 2.1.0
