### ISSUE TITLE
onError callback never called if payment was declined

### ISSUE THREAD

**Issue by AntonPetrov83** [xsolla/store-unity-sdk#67]
I am using the test card with the declined payment:

4111111111111178 (from [here](https://developers.xsolla.com/doc/pay-station/testing/test-cards/#pay_station_references_test_cards_decline))

After I press "Pay" button there appears a 3D secure chack page.
After this the browser get closed.

The `onBrowseClosed` callback gets called but `onError` callback is not, looks like a not very nice behaviour.

Our game blocks purchasing slot in the store and waits the result of the payment forever.

**Comment by DenisRakhimovXsolla** [comment]
Hey, @AntonPetrov83 !
Thank you for you issue
Will be fixed in next release

**Comment by DenisRakhimovXsolla** [comment]
But I think this shouldn't trigger the `onError` callback because it's not a payment system error.
Rather, the browser should not automatically close, allowing the user to complete the purchase in another way.
